'use client';
import AppShell from "../../components/AppShell";
import Metric from "../../components/Metric";
import Link from "next/link";
import { ArrowUpRight, Activity, BrainCircuit } from "lucide-react";

const assets=[["BTC/USD","$104,820.12","+2.84%"],["ETH/USD","$3,812.42","+1.62%"],["AAPL","$227.81","+0.91%"],["NVDA","$146.38","-0.42%"],["TSLA","$342.91","+1.34%"],["EUR/USD","1.0842","-0.18%"]];
export default function Dashboard(){return <AppShell><div className="mb-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm font-medium text-[#2563EB]">OVERVIEW</div><h1 className="mt-1 text-3xl font-bold">Market environment</h1><p className="mt-1 text-sm text-slate-500">A structured view of your current analytical context.</p></div><Link href="/analysis" className="rounded-lg bg-[#2563EB] px-4 py-2.5 text-sm font-medium text-white">Start Analysis</Link></div></div>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Selected Asset" value="BTC/USD"/><Metric label="Current Price" value="$104,820.12" change="+2.84% today"/><Metric label="Volatility" value="31.2%" change="Elevated context"/><Metric label="Market Sentiment" value="Positive" change="Contextual signal"/></div>
<div className="mt-4 grid gap-4 lg:grid-cols-3"><section className="card lg:col-span-2"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold">Watchlist Preview</h2><p className="text-xs text-slate-500">Selected market universe</p></div><Link href="/watchlist" className="text-sm font-medium text-[#2563EB]">View all</Link></div><div className="divide-y divide-slate-100">{assets.map(a=><Link href="/analysis" key={a[0]} className="flex items-center justify-between p-4 hover:bg-slate-50"><div><b className="text-sm">{a[0]}</b><div className="text-xs text-slate-500">Live-ready · Demo data</div></div><div className="text-right"><b className="text-sm">{a[1]}</b><div className={`text-xs ${a[2].startsWith("-")?"text-red-600":"text-green-600"}`}>{a[2]}</div></div></Link>)}</div></section>
<section className="card p-5"><div className="flex items-center gap-2 text-[#06B6D4]"><BrainCircuit size={18}/><span className="text-xs font-bold tracking-wide">AI MARKET INSIGHT</span></div><h2 className="mt-4 text-lg font-semibold">BTC/USD is showing elevated volatility around the selected timeframe.</h2><ul className="mt-4 space-y-3 text-sm text-slate-600"><li>• Momentum is weakening</li><li>• Trading volume has increased</li><li>• Price is approaching a resistance zone</li></ul><Link href="/ai-analyst" className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-[#2563EB]">View detailed analysis <ArrowUpRight size={15}/></Link></section></div>
<div className="mt-4 grid gap-4 md:grid-cols-3"><div className="card p-5"><Activity className="text-[#2563EB]"/><h3 className="mt-4 font-semibold">Workflow status</h3><p className="mt-1 text-sm text-slate-500">Asset selected → chart ready → AI context available.</p></div><div className="card p-5"><h3 className="font-semibold">Data status</h3><p className="mt-2 text-sm text-slate-500">Demo data is clearly labelled. Connect a provider key for live data.</p></div><div className="card p-5"><h3 className="font-semibold">Last updated</h3><p className="mt-2 text-sm text-slate-500">Just now · Demo environment</p></div></div></AppShell>}
